[package]
name = "socket_server_hello_world"
version = "0.1.0"
authors = ["Ido Ben-Natan <ido.bennatan@gmail.com>"]
edition = "2018"

[dependencies]
bufstream = "0.1"

[[bin]]
name = "relay-agent"
path = "src/relay_agent.rs"
